spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

brevo.sender.email=${MAIL_USERNAME}
brevo.api.key=${BREVO_API_KEY}
brevo.sender.name=${BREVO_SENDER_NAME}
brevo.api.url=${BREVO_API_URL}

logging.level.com.familywishes=INFO

app.jwt.secret=${JWT_SECRET}
app.gemini.api.key=${GEMINI_API_KEY}
app.gemini.api.url = ${GEMINI_API_URL}
app.huggingface.image.url = ${HUGGINGFACE_IMAGE_URL}
app.huggingface.image.key=${HUGGINGFACE_IMAGE_KEY}
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

scheduler.time-zone=Asia/Kolkata

alert.failure.threshold=5
alert.email.to=${MAIL_USERNAME}
management.endpoints.web.exposure.include=*

# Instagram Graph API
instagram.graph-url=https://graph.facebook.com/v18.0
instagram.page-access-token=YOUR_PAGE_ACCESS_TOKEN

# Async thread pool
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=100

spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=always
spring.quartz.properties.org.quartz.scheduler.instanceName=FamilyWishesScheduler
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
spring.quartz.properties.org.quartz.jobStore.class=org.springframework.scheduling.quartz.LocalDataSourceJobStore
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.quartz.properties.org.quartz.jobStore.useProperties=false
spring.quartz.properties.org.quartz.jobStore.tablePrefix=QRTZ_
spring.quartz.properties.org.quartz.jobStore.isClustered=true
spring.quartz.properties.org.quartz.threadPool.threadCount=5

gmail.client-id=${GMAIL_CLIENT_ID}
gmail.client-secret=${GMAIL_CLIENT_SECRET}
gmail.refresh-token=${GMAIL_REFRESH_TOKEN}
gmail.from-email=${GMAIL_FROM_EMAIL}

instagram.verify.token=${INSTA_VERIFY_TOKEN}